config/routes.rb
UrlShortener::Application.routes.draw do
  get '/s/:unique_path', to: 'shorteners#translate'   
  resources :shorteners

  root :to => 'shorteners#index'

end

app/models/shortener.rb
class Shortener < ActiveRecord::Base
  attr_accessible :orig_url, :shortened_url
  UNIQUE_PATH_LENGTH = 5
  HOST_NAME = 'http://dry-cliffs-6195.herokuapp.com'
  def self.generate orig_url
    shortener = find_by_orig_url orig_url
    return shortener if shortener

    begin
      unique_path = generate_random_string UNIQUE_PATH_LENGTH
    end while find_by_shortened_url unique_path
    shortener = create orig_url: orig_url, shortened_url: shortened_url(unique_path)
    shortener
  end

  def self.generate_random_string length=5
    char_set= ('a'..'z').to_a + (0..9).to_a
    (0..length).map { char_set[rand(char_set.size)]}.join
  end

  def self.shortened_url unique_path
    "#{HOST_NAME}/s/#{unique_path}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shorteners_controller.rb
class ShortenersController < ApplicationController
  # GET /shorteners
  # GET /shorteners.json
  def index
    @shorteners = Shortener.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shorteners }
    end
  end

  # GET /shorteners/1
  # GET /shorteners/1.json
  def show
    @shortener = Shortener.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shortener }
    end
  end

  # GET /shorteners/new
  # GET /shorteners/new.json
  def new
    @shortener = Shortener.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shortener }
    end
  end

  # GET /shorteners/1/edit
  def edit
    @shortener = Shortener.find(params[:id])
  end

  # POST /shorteners
  # POST /shorteners.json
  def create
    orig_url = params[:shortener][:orig_url]
    @shortener = Shortener.generate orig_url
    respond_to do |format|
      if @shortener.save
        format.html { redirect_to @shortener, notice: 'Shortener was successfully created.' }
        format.json { render json: @shortener, status: :created, location: @shortener }
      else
        format.html { render action: "new" }
        format.json { render json: @shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shorteners/1
  # PUT /shorteners/1.json
  def update
    @shortener = Shortener.find(params[:id])

    respond_to do |format|
      if @shortener.update_attributes(params[:shortener])
        format.html { redirect_to @shortener, notice: 'Shortener was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shorteners/1
  # DELETE /shorteners/1.json
  def destroy
    @shortener = Shortener.find(params[:id])
    @shortener.destroy

    respond_to do |format|
      format.html { redirect_to shorteners_url }
      format.json { head :no_content }
    end
  end

  def translate
    url = Shortener.shortened_url params[:unique_path]
    su = Shortener.find_by_shortened_url url
    if su
      redirect_to su.orig_url, :status => :moved_permanently 
    else
      redirect_to '/'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorteners_helper.rb
module ShortenersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "URL Shortener" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "URL Shortener", shorteners_path %></a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <li><%= link_to "List Shorteners", shorteners_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Contact Us" %></li>
        </ul>
      </section>
    </nav>
    
    <div class="row">
      <div class="small-12 columns"><%= yield %></div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shorteners/_form.html.erb
<%= form_for(@shortener) do |f| %>
  <% if @shortener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shortener.errors.count, "error") %> prohibited this shortener from being saved:</h2>

      <ul>
      <% @shortener.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :orig_url %><br />
    <%= f.text_field :orig_url %>
  </div>
  <div class="field">
    <%= f.label :shortened_url %><br />
    <%= f.text_field :shortened_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shorteners/edit.html.erb
<h1>Editing shortener</h1>

<%= render 'form' %>

<%= link_to 'Show', @shortener %> |
<%= link_to 'Back', shorteners_path %>

app/views/shorteners/index.html.erb
<h1>Listing shorteners</h1>

<table>
  <tr>
    <th>Orig url</th>
    <th>Uniuqe path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shorteners.each do |shortener| %>
  <tr>
    <td><%= shortener.orig_url %></td>
    <td><%= shortener.shortened_url %></td>
    <td><%= link_to 'Show', shortener %></td>
    <td><%= link_to 'Edit', edit_shortener_path(shortener) %></td>
    <td><%= link_to 'Destroy', shortener, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shortener', new_shortener_path %>

app/views/shorteners/new.html.erb
<h1>New shortener</h1>
<%= form_for(@shortener) do |f| %>
  <% if @shortener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shortener.errors.count, "error") %> prohibited this shortener from being saved:</h2>

      <ul>
      <% @shortener.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :orig_url %><br />
    <%= f.text_field :orig_url, placeholder: 'http://exaple.com' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', shorteners_path %>

app/views/shorteners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Orig url:</b>
  <%= @shortener.orig_url %>
</p>

<p>
  <b>Uniuqe path:</b>
  <%= @shortener.shortened_url %>
</p>


<%= link_to 'Edit', edit_shortener_path(@shortener) %> |
<%= link_to 'Back', shorteners_path %>